#!/usr/bin/env bash
# Usage: pj scripts push
# Summary: This script will push any changes currently commited to the payjoy_scripts github repo
# Help: Please review the script itself before use

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

ver=`cat $SCRIPT_DIR/../../.version`

ver=`expr $ver + 1`

echo $ver > $SCRIPT_DIR/../../.version

cd $SCRIPT_DIR/../..

git add .version

git commit -m 'Incrementing Version'

# get current branch 
branch=`git symbolic-ref -q HEAD`

git checkout master

git pull origin master

git merge $branch

git push origin master

