#!/usr/bin/env bash
# Usage: pj commands
# Summary: List all pj commands
# Help: This command is mostly used for autocompletion in various shells, and for `pj help`.
# Also, this command helps find commands that are named the same as potentially builtin shell commands (which, cd, etc)

set -e

vars=($@)

for (( i=0; i < ${#vars[@]}; i++ )); do

  if [ "${vars[$i]}" == "--fullpath" ]; then

    export _SUB_FULL="true"

  fi

done

if [ ! -z "$1" ] && [ -f $1 ]; then

  if [[ "$(basename $1)" != "$1" ]]; then

    name=$(dirname $1)
    export _SUB_COMMAND_HELP_DIR=$name

  fi

fi

if [ "$1" = "--sh" ]; then
  sh=1
  shift
elif [ "$1" = "--no-sh" ]; then
  nosh=1
  shift
fi

shopt -s nullglob

if [ -f "$_SUB_COMMAND_ROOT/pj-$_SUB_COMMAND_FILE" ]; then

  if grep -i "^# provide pj completions" "$_SUB_COMMAND_ROOT/pj-$_SUB_COMMAND_FILE" >/dev/null; then
    completions=`exec "$_SUB_COMMAND_ROOT/pj-$_SUB_COMMAND_FILE" --complete "$@"`
    if [ "$completions" ]; then
      echo $completions
    fi
    exit
  fi

else

  if grep -i "^# provide pj completions" "$_SUB_COMMAND_ROOT/$_SUB_COMMAND_FILE" >/dev/null; then
    completions=`exec "$_SUB_COMMAND_ROOT/$_SUB_COMMAND_FILE" --complete "$@"`
    if [ "$completions" ]; then
      echo $completions
    fi
    exit
  fi

fi

{ 
  for path in ${_SUB_COMMAND_HELP_DIR//:/$'\n'}; do
    for command in "$path/pj-*"; do

      a=($command)

      for i in "${a[@]}"
      do

        if [ ! -z $1 ] && [ -f $1 ]; then
          d=$(basename $1)
        else
          d="sdafagsdg"
        fi

        if [ -f $i ]; then
          e=$(basename $i)
          f=$(basename $(dirname $i))
        else
          e="agdrgag"
          f="adfrtsh"
        fi

        if [ "$e" == "$f" ]; then
          continue
        fi

        c=$(basename $i)

        if [ "$c" != "pj-$1" ] && [ "$c" != "$d" ]; then
          b=${c##pj-}

          if [ "$_SUB_FULL" == "true" ] && [ "$c" != "$0" ]; then

            echo $i
          else

            echo $b
          fi
        fi
      
      done
      
    done
  done
} | sort | uniq
