#!/usr/bin/env php
# Usage: pj config get [<var>]
# Summary: Retrieve configurable variables from conf/config.yaml
# Help: Use this command to retrieve configurable variables in conf/config.yaml

pj help config get