#!/usr/bin/env php
<?php
# Usage: pj config get [<var>]
# Summary: Retrieve configurable variables from conf/config.yaml
# Help: Use this command to retrieve configurable variables in conf/config.yaml

// Bootstrap!
require(getenv('_PJ_ROOT') .'/libexec/pj-config/lib/init.php');

// Get params
$params = $argv;
unset($params[0]);
unset($params[1]);

// Show config
echo get_config_by_params($params);

/**
 * Gets config items by space-deliminated list of paramaters
 *
 * @return string
 * @author Jake A. Smith
 **/
function get_config_by_params($params)
{
	// Default return empty string
	$return = '';

	$config = config();
	foreach($params as $arg)
	{
		// If the var doesn't exist just return empty string
		if(!isset($config[$arg]))
			return $return;

		// Drill down
		$config = $config[$arg];
	}

	// Show everything that's not an array
	if(!is_array($config))
	{
		$return = $config . PHP_EOL;
	}

	// Show array keys
	if(is_array($config))
	{
		foreach(array_keys($config) as $key)
		{
			$return .= $key . PHP_EOL;
		}
	}

	return $return;
}

